# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11ea75dc9ccbcd39df0e86335a092e01b7fffac7a5dafa1dffafd690d836c3cd9305b49b24224de33cb341f872bb62692fcef8ab37330c74e33f3a94207e8d56

test:
  secret_key_base: 26aacd9c7f831054a191b0f5b9f51e03c97772180b73c0656b9a5c8833dd12bd014cb23dcd39c1924666cc974d7e06b637062f5620dbf1aa39370208756c6fa4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
